package com.netflix.spinnaker.keel.migrations

import com.netflix.spinnaker.keel.core.api.SubmittedDeliveryConfig


/**
 * An Object containing the data needed in order to open a PR for an application with a config file.
 */
data class ApplicationPrData (
  val autoGeneratedConfig: SubmittedDeliveryConfig,
  val userGeneratedConfig: SubmittedDeliveryConfig? = null,
  val repoSlug: String,
  val projectKey: String,
  val prLink: String? = null
) {
  // we first check if we have any config generated by the user (meaning, was edited before), and fallback to the one we originally exported
  val deliveryConfig: SubmittedDeliveryConfig
    get() = userGeneratedConfig ?: autoGeneratedConfig
}
