package com.netflix.spinnaker.keel.api.migration

import java.time.Instant


data class UserGeneratedConfig(
  val config: Map<String, Any?>,
  val updatedAt: Instant?,
  val updatedBy: String?
)


data class ApplicationMigrationStatus(
  val exportSucceeded: Boolean = false,
  val inAllowList: Boolean = false,
  val assistanceNeeded: Boolean = false,
  val alreadyManaged: Boolean = false,
  val autoGeneratedConfig: Map<String, Any?>? = null,
  val userGeneratedConfig: UserGeneratedConfig? = null,
  val prLink: String? = null,
  val jiraLink: String? = null,
  val pipelines: List<MigrationPipeline>? = null
) {
  val isMigratable: Boolean
    get() = exportSucceeded && inAllowList

  val isBlocked: Boolean
    get() = assistanceNeeded
}
